DROP database IF EXISTS FITNESS;

create database FITNESS;

use FITNESS;

DROP TABLE IF EXISTS `MEMBER`;

CREATE TABLE `MEMBER` (
	`MEMBER_ID`	int	PRIMARY KEY AUTO_INCREMENT,
	`NAME`	varchar(20)	NOT NULL,
	`CONTACT`	varchar(13)	NOT NULL,
	`JOIN_DATE`	DATETIME	NOT NULL default current_timestamp,#현재시간 가입하기
	`LOCKER_ID`	int unique NULL
);

DROP TABLE IF EXISTS `LOCKER`;

CREATE TABLE `LOCKER` (
	`LOCKER_ID`	int	PRIMARY KEY AUTO_INCREMENT,
	`LOCATION`	varchar(10)	NOT NULL
);

DROP TABLE IF EXISTS `CLASS`;

CREATE TABLE `CLASS` (
	`CLASS_ID`	INT	PRIMARY KEY AUTO_INCREMENT,
	`NAME`	varchar(20)	NOT NULL,
	`CAPACITY`	int	NOT NULL,
	`FEE`	int	NOT NULL,
	`TRAINER_ID`	int	NOT NULL
);

DROP TABLE IF EXISTS `TRAINER`;

CREATE TABLE `TRAINER` (
	`TRAINER_ID`	int	PRIMARY KEY AUTO_INCREMENT,
	`NAME`	varchar(20)	NOT NULL,
	`SPECIALTY`	varchar(20)	NULL,
	`EXPERIENCE`	INT	NOT NULL default 0,
	`MANAGER_ID`	int NULL
);

DROP TABLE IF EXISTS `ENROLLMENT`;

CREATE TABLE `ENROLLMENT` (
	`ENROLLMENT_ID`	INT	PRIMARY KEY AUTO_INCREMENT,
	`APPLY_DATE`	DATETIME	NOT NULL default current_timestamp,
	`PAYMENT_STATE`	varchar(3)	NOT NULL,
	`MEMBER_ID`	int	NOT NULL,
	`CLASS_ID`	INT	NOT NULL
);

DROP TABLE IF EXISTS `ATTENDANCE`;

CREATE TABLE `ATTENDANCE` (
	`ATTENDANCE_ID`	INT	PRIMARY KEY AUTO_INCREMENT,
	`CHECK_IN_TIME`	DATETIME	NOT NULL default current_timestamp,
	`MEMBER_ID`	int	NOT NULL,
	`CLASS_ID`	INT	NOT NULL
);

ALTER TABLE `MEMBER` ADD CONSTRAINT `FK_LOCKER_TO_MEMBER_1` FOREIGN KEY (
	`LOCKER_ID`
)
REFERENCES `LOCKER` (
	`LOCKER_ID`
);

ALTER TABLE `CLASS` ADD CONSTRAINT `FK_TRAINER_TO_CLASS_1` FOREIGN KEY (
	`TRAINER_ID`
)
REFERENCES `TRAINER` (
	`TRAINER_ID`
);

ALTER TABLE `TRAINER` ADD CONSTRAINT `FK_TRAINER_TO_TRAINER_1` FOREIGN KEY (
	`MANAGER_ID`
)
REFERENCES `TRAINER` (
	`TRAINER_ID`
);

ALTER TABLE `ENROLLMENT` ADD CONSTRAINT `FK_MEMBER_TO_ENROLLMENT_1` FOREIGN KEY (
	`MEMBER_ID`
)
REFERENCES `MEMBER` (
	`MEMBER_ID`
);

ALTER TABLE `ENROLLMENT` ADD CONSTRAINT `FK_CLASS_TO_ENROLLMENT_1` FOREIGN KEY (
	`CLASS_ID`
)
REFERENCES `CLASS` (
	`CLASS_ID`
);

ALTER TABLE `ATTENDANCE` ADD CONSTRAINT `FK_MEMBER_TO_ATTENDANCE_1` FOREIGN KEY (
	`MEMBER_ID`
)
REFERENCES `MEMBER` (
	`MEMBER_ID`
);

ALTER TABLE `ATTENDANCE` ADD CONSTRAINT `FK_CLASS_TO_ATTENDANCE_1` FOREIGN KEY (
	`CLASS_ID`
)
REFERENCES `CLASS` (
	`CLASS_ID`
);

