spring.application.name=practice
spring.thymeleaf.cache=false
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/p?useSSL=false&serverTimezone=Asia/Seoul
# 1. XML 위치 알려주기 (src/main/resources/mapper 폴더 안의 모든 xml)
mybatis.mapper-locations=classpath:mappers/*.xml